### ISSUE TITLE
Twitter is not searching for "Remdesivir or Tocilizumab" even Medicine is selected tab

### ISSUE THREAD

**Issue by technoknol** [coronasafe/life#228]
**Is your feature request related to a problem? Please describe.**
If I want to search for Remdesivir or Tocilizumab I'm unable to get it. Right now twitter query is searching for verified Oxygen, Ventilators and Bed even when I'm on medicine tab.

**Describe the solution you'd like**
Medicine and All tab should search for Remdesivir or Tocilizumab or any other critical relative medicine. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by minkeshj** [comment]
I believe this issue has been resolved already. We can close it.
![image](https://user-images.githubusercontent.com/60917559/116920639-8570aa00-ac70-11eb-9c3c-c4efc1f096f6.png)

**Comment by viksit** [comment]
No this is not solved. 

The way to solve this is,

- map medicines to a list of medicines [medrol, dolo, ...]
- call the Twitter search api with a new parameter called resource_type_detail=medicine&resource_meta=dolo,medrol.. (comma separated string of the above list)
- Ping @sumit or @apoorv singal in the search channel on slack to have them integrate this in the Twitter search backend

**Comment by n3jain** [comment]
@viksit It looks like the covidConnect API for twitter search only supports two kinds of resource_type filtering 1. Supply 2. Demand. Also, the search string is constructed only from the location, doesn't take into the resource type or district. In order to make the twitter search appropriate based on the resource type and district, the updates need to be done for the covidconnect API. Could you please point to where the covid connect repository is, so that I can expand the feature set for that API?

**Comment by brainless** [comment]
@n3jain let me have a look at this today. @apoorvsingal and myself are in the covidconnect repo. If you have time right now then please feel free to make the changes, I can review the PR. The repo is at https://github.com/viksit/covidconnect

**Comment by minkesh** [comment]
@brainless @viksit I have raised the PR to integrate the changes done by @n3jain to support searching of medicines via covidconnect api. Now we have capability to search for required resources on twitter (previously it was a fixed hardcoded query).

**Comment by minkeshj** [comment]
https://github.com/coronasafe/life/pull/268
